apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - image: dbeaver/cloudbeaver:latest
          imagePullPolicy: Always
          name: cloudbeaver4
          ports:
            - containerPort: 8978
          volumeMounts:
            - mountPath: /opt/cloudbeaver/workspace
              name: cloudbeaver-pv
      volumes:
        - name: cloudbeaver-pv
          persistentVolumeClaim:
            claimName: cloudbeaver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  selector:
    app: cloudbeaver
  type: NodePort
  ports:
    - port: 8978
      nodePort: 30082           
