apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@example.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: pgadmin
            - name: PGADMIN_PORT
              value: "80"
          image: "dpage/pgadmin4:snapshot"
          imagePullPolicy: Always
          name: pgadmin4
          ports:
            - containerPort: 80
              name: pgadminport
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-pv
      volumes:
        - name: pgadmin-pv
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
