kind: PersistentVolume
apiVersion: v1
metadata:
  name: mxcrmpdb-pv
  namespace: database
  labels:
    app: mxcrmpdb
spec:
  storageClassName: ""
  capacity:
    storage: 1G
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.3.105.69
    path: "/var/nfs/k8sdev/database/mxcrmpdb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mxcrmpdb-pvc
  namespace: database
  labels:
    app: mxcrmpdb
spec:
  volumeName: mxcrmpdb-pv
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100M
