apiVersion: v1
kind: ConfigMap
metadata:
  name: pghero
data:
  pghero.yml: |-
    databases:
      main:
        url: postgres://pghero:postgres4hero@10.3.150.43:5432/postgres?sslmode=disable
      etaxdb:
        url: postgres://pghero:postgres4hero@10.3.150.43:5432/etaxdb?sslmode=disable
        capture_query_stats: main
      epmdb:
        url: postgres://pghero:postgres4hero@10.3.150.43:5432/epmdb?sslmode=disable
        capture_query_stats: main
      dmsdb:
        url: postgres://pghero:postgres4hero@10.3.150.43:5432/dmsdb?sslmode=disable
        capture_query_stats: main
      signdb:
        url: postgres://pghero:postgres4hero@10.3.150.43:5432/signdb?sslmode=disable
        capture_query_stats: main

    # Minimum time for long running queries
    # long_running_query_sec: 60

    # Minimum average time for slow queries
    # slow_query_ms: 20

    # Minimum calls for slow queries
    # slow_query_calls: 100

    # Minimum connections for high connections warning
    # total_connections_threshold: 500

    # Statement timeout for explain
    # explain_timeout_sec: 10

    # Time zone
    # time_zone: "Pacific Time (US & Canada)"
---
apiVersion: v1
kind: Service
metadata:
  name: pghero
  labels:
    app: pghero
spec:
  selector:
    app: pghero
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pghero
  labels:
    app: pghero
spec:
  selector:
    matchLabels:
      app: pghero
  replicas: 1
  template:
    metadata:
      labels:
        app: pghero
    spec:
      containers:
      - name: pghero
        image: ankane/pghero
        imagePullPolicy: Always
        volumeMounts:
        - name: pghero-configmap
          mountPath: /app/config/pghero.yml
          readOnly: true
          subPath: pghero.yml
      volumes:
      - name: pghero-configmap
        configMap:
          defaultMode: 0644
          name: pghero
