apiVersion: apps/v1
kind: Deployment
metadata:
  name: cibdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cibdb
  template:
    metadata:
      labels:
        app: postgres-cibdb
    spec:
      containers:
        - name: postgres
          image: postgres:13.6
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "500Mi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: cibdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: isylzjkodev
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: cibdb-pvc
---
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres-cibdb
      labels:
        app: postgres-cibdb
    spec:
       ports:
        - name: postgres-cibdb
          port: 5432
       type: NodePort
       selector:
        app: postgres-cibdb
