kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloudbeaver-pv
  namespace: database
  labels:
    app: cloudbeaver
spec:
  storageClassName: ""
  capacity:
    storage: 1G
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.3.140.21
    path: "/KUBE1/database/cloudbeaver"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloudbeaver-pvc
  namespace: database
  labels:
    app: cloudbeaver
spec:
  volumeName: cloudbeaver-pv
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100M
