apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratel
  template:
    metadata:
      labels:
        app: ratel
    spec:
      containers:
        - image: "dgraph/ratel:v21.12.0"
          imagePullPolicy: IfNotPresent
          name: ratel
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ratel
  labels:
    app: ratel
spec:
  selector:
    app: ratel
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30086
